export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";

export const LOAD_MODAL = "LOAD_MODAL";
export const REMOVE_MODAL = "REMOVE_MODAL";

export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";

export const UPDATE_USER_PROFILE_IMAGE = "UPDATE_USER_PROFILE_IMAGE";
